export const columnModel = [
  {
    actionable: true,
    background: "#ffff00",
    filters: [],
    frozen: false,
    hideable: false,
    id: "actions",
    label: "Action",
    order: 0,
    reorderable: false,
    sortable: false,
    sort: "none",
    visible: true,
    width: 50,
  },
  {
    actionable: false,
    background: "white",
    filters: [],
    frozen: false,
    hideable: true,
    id: "file",
    label: "File",
    order: 1,
    reorderable: true,
    sortable: true,
    sort: "none",
    visible: true,
    width: 250,
  },
  {
    actionable: false,
    background: "white",
    filters: [],
    frozen: false,
    hideable: true,
    id: "type",
    label: "Type",
    order: 2,
    reorderable: true,
    sortable: false,
    sort: "none",
    visible: true,
    width: 60,
  },
  {
    actionable: false,
    background: "white",
    filters: [],
    frozen: false,
    hideable: true,
    id: "shortName",
    label: "Short Name",
    order: 3,
    reorderable: true,
    sortable: true,
    sort: "none",
    visible: true,
    width: 150,
  },
  {
    actionable: false,
    background: "white",
    filters: [],
    frozen: false,
    hideable: true,
    id: "size",
    label: "Size",
    order: 4,
    reorderable: true,
    sortable: true,
    sort: "none",
    visible: true,
    width: 100,
  },
  {
    actionable: false,
    background: "white",
    filters: [],
    frozen: false,
    hideable: true,
    id: "progress",
    label: "Progress",
    order: 5,
    reorderable: true,
    sortable: true,
    sort: "none",
    visible: true,
    width: 250,
  },
  {
    actionable: false,
    background: "white",
    filters: [],
    frozen: false,
    hideable: true,
    id: "folder",
    label: "Folder",
    order: 6,
    reorderable: true,
    sortable: true,
    sort: "none",
    visible: true,
    width: 150,
  },
];